"""initial schema

The baseline: the six tables the application has always had, captured as a
migration so that from here every schema change has a reviewed, reversible
step instead of arriving as an edit to `db.py` that only a fresh database
would ever pick up.

Autogenerated against an empty database from `finvault.db.metadata`, so it
is by construction identical to what `metadata.create_all` produced before
— an existing deployment can therefore be stamped rather than migrated:

    alembic stamp 4438101f076d

Not covered here, deliberately: Row Level Security. The policies are not
schema in the DDL sense — they are re-derived and reinstalled idempotently
on every deploy from `RLS_TABLES` in `security/rls.py`, which keeps a policy
change from needing a migration and keeps `verify_isolation` the single
authority on whether isolation is actually in force. `finvault-migrate`
runs both steps in the right order (see `finvault/migrate.py`).

Revision ID: 4438101f076d
Revises:
Create Date: 2026-08-31 22:44:29.112373

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4438101f076d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "audit_log",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(), nullable=False),
        sa.Column("entry_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_org_id"), "documents", ["org_id"], unique=False)
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("source_node_id", sa.String(), nullable=False),
        sa.Column("target_node_id", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("relation_encrypted", sa.JSON(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_edges_classification"), "graph_edges", ["classification"], unique=False)
    op.create_index(op.f("ix_graph_edges_org_id"), "graph_edges", ["org_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_source_node_id"), "graph_edges", ["source_node_id"], unique=False)
    op.create_index(op.f("ix_graph_edges_target_node_id"), "graph_edges", ["target_node_id"], unique=False)
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("source_document_id", sa.String(), nullable=True),
        sa.Column("label_hash", sa.String(), nullable=False),
        sa.Column("label_encrypted", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_nodes_classification"), "graph_nodes", ["classification"], unique=False)
    op.create_index(op.f("ix_graph_nodes_label_hash"), "graph_nodes", ["label_hash"], unique=False)
    op.create_index(op.f("ix_graph_nodes_org_id"), "graph_nodes", ["org_id"], unique=False)
    op.create_table(
        "review_queue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("draft_answer", sa.String(), nullable=False),
        sa.Column("block_reason", sa.String(), nullable=True),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.Float(), nullable=True),
        sa.Column("reviewer_note", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_queue_org_id"), "review_queue", ["org_id"], unique=False)
    op.create_index(op.f("ix_review_queue_status"), "review_queue", ["status"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_session_id"), "sessions", ["session_id"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_review_queue_status"), table_name="review_queue")
    op.drop_index(op.f("ix_review_queue_org_id"), table_name="review_queue")
    op.drop_table("review_queue")
    op.drop_index(op.f("ix_graph_nodes_org_id"), table_name="graph_nodes")
    op.drop_index(op.f("ix_graph_nodes_label_hash"), table_name="graph_nodes")
    op.drop_index(op.f("ix_graph_nodes_classification"), table_name="graph_nodes")
    op.drop_table("graph_nodes")
    op.drop_index(op.f("ix_graph_edges_target_node_id"), table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_source_node_id"), table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_org_id"), table_name="graph_edges")
    op.drop_index(op.f("ix_graph_edges_classification"), table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(op.f("ix_documents_org_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("audit_log")
