"""Persisted store for extracted knowledge-graph entities/relationships.

Encryption-agnostic, like retrieval/vector_store.py — this module never
encrypts or decrypts anything itself. Encrypting `label`/`relation` before
insert (ingestion/pipeline.py) and decrypting after the ACL check
(retrieval/graph_retriever.py) both happen in the caller, exactly mirroring
how VectorStore/Retriever split those responsibilities for chunk text. The
`Raw*` dataclasses here (still-encrypted) are the store's native shape;
canvas_models.py's GraphNode/GraphEdge (plaintext label/relation) only ever
get constructed downstream, in GraphRetriever, for entries that already
passed the ACL check.

Deduplication: upsert_node finds an existing node by (org_id, type,
label_hash) before creating a new one — simple exact-match dedup, not fuzzy
entity resolution. "Acme Capital Partners" and "Acme Capital" become two
separate nodes; that's a deliberate, documented scope limit (see
ingestion/extraction.py), not an oversight.
"""

from __future__ import annotations

import hashlib
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any
from uuid import uuid4

from sqlalchemy import insert, select
from sqlalchemy.engine import Engine

from finvault.agents.canvas_models import GraphEntityType
from finvault.db import graph_edges_table, graph_nodes_table
from finvault.security.encryption import EncryptedPayload


def normalize_label(label: str) -> str:
    """Canonical normalization for fuzzy entity resolution: lowercases, strips
    whitespace, and removes common legal/corporate entity suffixes (e.g. Inc,
    Corp, LLC, Limited, Co, Corporation) so that 'Acme Capital Inc.', 'Acme Capital,
    LLC', and 'Acme Capital' resolve to the exact same canonical entity node.
    """
    clean = label.strip().lower()
    # Strip common punctuation (commas, periods)
    clean = re.sub(r"[,.]", "", clean)
    # Strip trailing corporate suffixes
    clean = re.sub(r"\b(inc|corp|corporation|llc|ltd|limited|co|company|group|holdings|plc)\b$", "", clean).strip()
    return clean or label.strip().lower()


def label_hash(org_id: str, entity_type: str, label: str) -> str:
    """Deterministic (unkeyed) dedup key — see db.py's module docstring for
    why this is not a secrecy boundary.
    """
    payload = f"{org_id}:{entity_type}:{normalize_label(label)}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def node_aad(org_id: str, entity_type: str, node_label_hash: str) -> bytes:
    """Bound to (org_id, type, label_hash) rather than the node's own id —
    deliberately, so the AAD is computable *before* upsert_node runs (which
    may return an existing id via dedup, not a fresh one), avoiding a
    chicken-and-egg ordering problem between "encrypt the label" and
    "find out what id this node ends up with."
    """
    return f"graph_node:{org_id}:{entity_type}:{node_label_hash}".encode()


def edge_aad(edge_id: str) -> bytes:
    # Edges aren't deduplicated (see ingestion/extraction.py), so a fresh id
    # is always generated by the caller before encryption — no ordering
    # problem here, unlike node_aad above.
    return f"graph_edge:{edge_id}".encode()


@dataclass(frozen=True)
class RawGraphNode:
    id: str
    org_id: str
    type: GraphEntityType
    classification: str
    source_document_id: str | None
    label_hash: str
    label_encrypted: EncryptedPayload
    details: dict[str, Any]


@dataclass(frozen=True)
class RawGraphEdge:
    id: str
    org_id: str
    source_node_id: str
    target_node_id: str
    classification: str
    relation_encrypted: EncryptedPayload
    weight: float


class GraphStore(ABC):
    @abstractmethod
    def upsert_node(
        self,
        *,
        org_id: str,
        type: GraphEntityType,
        classification: str,
        source_document_id: str | None,
        node_label_hash: str,
        label_encrypted: EncryptedPayload,
    ) -> RawGraphNode: ...

    @abstractmethod
    def add_edge(
        self,
        *,
        id: str,
        org_id: str,
        source_node_id: str,
        target_node_id: str,
        classification: str,
        relation_encrypted: EncryptedPayload,
        weight: float = 1.0,
    ) -> RawGraphEdge: ...

    @abstractmethod
    def get_nodes_and_edges(self, *, org_id: str) -> tuple[list[RawGraphNode], list[RawGraphEdge]]: ...


class InMemoryGraphStore(GraphStore):
    """Reference implementation — not persisted across process restarts,
    same pattern as InMemoryAuditLog/InMemorySessionStore/InMemoryReviewQueue.
    """

    def __init__(self) -> None:
        self._nodes: dict[str, RawGraphNode] = {}
        self._edges: dict[str, RawGraphEdge] = {}

    def upsert_node(
        self,
        *,
        org_id: str,
        type: GraphEntityType,
        classification: str,
        source_document_id: str | None,
        node_label_hash: str,
        label_encrypted: EncryptedPayload,
    ) -> RawGraphNode:
        for existing in self._nodes.values():
            if existing.org_id == org_id and existing.type == type and existing.label_hash == node_label_hash:
                return existing

        node = RawGraphNode(
            id=str(uuid4()),
            org_id=org_id,
            type=type,
            classification=classification,
            source_document_id=source_document_id,
            label_hash=node_label_hash,
            label_encrypted=label_encrypted,
            details={},
        )
        self._nodes[node.id] = node
        return node

    def add_edge(
        self,
        *,
        id: str,
        org_id: str,
        source_node_id: str,
        target_node_id: str,
        classification: str,
        relation_encrypted: EncryptedPayload,
        weight: float = 1.0,
    ) -> RawGraphEdge:
        edge = RawGraphEdge(
            id=id,
            org_id=org_id,
            source_node_id=source_node_id,
            target_node_id=target_node_id,
            classification=classification,
            relation_encrypted=relation_encrypted,
            weight=weight,
        )
        self._edges[edge.id] = edge
        return edge

    def get_nodes_and_edges(self, *, org_id: str) -> tuple[list[RawGraphNode], list[RawGraphEdge]]:
        nodes = [n for n in self._nodes.values() if n.org_id == org_id]
        edges = [e for e in self._edges.values() if e.org_id == org_id]
        return nodes, edges


class PostgresGraphStore(GraphStore):
    """Persistent store backed by the `graph_nodes`/`graph_edges` tables
    (see db.py).

    Note: upsert_node's find-then-insert runs inside one transaction, which
    is correct for a single-writer/low-concurrency deployment — the same
    caveat already documented on PostgresAuditLog.append() applies here: a
    high-throughput multi-writer deployment could race two concurrent
    upserts of the same label into two rows instead of one.
    """

    def __init__(self, engine: Engine) -> None:
        self._engine = engine

    def upsert_node(
        self,
        *,
        org_id: str,
        type: GraphEntityType,
        classification: str,
        source_document_id: str | None,
        node_label_hash: str,
        label_encrypted: EncryptedPayload,
    ) -> RawGraphNode:
        with self._engine.begin() as conn:
            existing = conn.execute(
                select(graph_nodes_table).where(
                    graph_nodes_table.c.org_id == org_id,
                    graph_nodes_table.c.type == type,
                    graph_nodes_table.c.label_hash == node_label_hash,
                )
            ).first()
            if existing is not None:
                return _row_to_node(existing)

            node_id = str(uuid4())
            conn.execute(
                insert(graph_nodes_table).values(
                    id=node_id,
                    org_id=org_id,
                    type=type,
                    classification=classification,
                    source_document_id=source_document_id,
                    label_hash=node_label_hash,
                    label_encrypted=label_encrypted.to_dict(),
                    details={},
                )
            )
        return RawGraphNode(
            id=node_id,
            org_id=org_id,
            type=type,
            classification=classification,
            source_document_id=source_document_id,
            label_hash=node_label_hash,
            label_encrypted=label_encrypted,
            details={},
        )

    def add_edge(
        self,
        *,
        id: str,
        org_id: str,
        source_node_id: str,
        target_node_id: str,
        classification: str,
        relation_encrypted: EncryptedPayload,
        weight: float = 1.0,
    ) -> RawGraphEdge:
        with self._engine.begin() as conn:
            conn.execute(
                insert(graph_edges_table).values(
                    id=id,
                    org_id=org_id,
                    source_node_id=source_node_id,
                    target_node_id=target_node_id,
                    classification=classification,
                    relation_encrypted=relation_encrypted.to_dict(),
                    weight=weight,
                )
            )
        return RawGraphEdge(
            id=id,
            org_id=org_id,
            source_node_id=source_node_id,
            target_node_id=target_node_id,
            classification=classification,
            relation_encrypted=relation_encrypted,
            weight=weight,
        )

    def get_nodes_and_edges(self, *, org_id: str) -> tuple[list[RawGraphNode], list[RawGraphEdge]]:
        with self._engine.connect() as conn:
            node_rows = conn.execute(select(graph_nodes_table).where(graph_nodes_table.c.org_id == org_id)).all()
            edge_rows = conn.execute(select(graph_edges_table).where(graph_edges_table.c.org_id == org_id)).all()
        return [_row_to_node(row) for row in node_rows], [_row_to_edge(row) for row in edge_rows]


def _row_to_node(row: Any) -> RawGraphNode:
    return RawGraphNode(
        id=row.id,
        org_id=row.org_id,
        type=row.type,
        classification=row.classification,
        source_document_id=row.source_document_id,
        label_hash=row.label_hash,
        label_encrypted=EncryptedPayload.from_dict(row.label_encrypted),
        details=row.details,
    )


def _row_to_edge(row: Any) -> RawGraphEdge:
    return RawGraphEdge(
        id=row.id,
        org_id=row.org_id,
        source_node_id=row.source_node_id,
        target_node_id=row.target_node_id,
        classification=row.classification,
        relation_encrypted=EncryptedPayload.from_dict(row.relation_encrypted),
        weight=row.weight,
    )
